config/routes.rb
Rails.application.routes.draw do
  post 'search_flights', to: 'flight_bookings#find_location'
  delete 'search_flights', to: 'flight_bookings#destroy_flight_selection'
  
  devise_for :users
  root to: 'pages#home'

  resources :trips do
    resources :invitations, only: [ :new, :create ]
    resources :flight_bookings, only: [ :new, :create ]
    get 'search_flights', to: 'flight_bookings#flight_search'
  end
  
  resources :invitations, only: [ :index, :show, :update ]

  resources :flight_bookings, only: [ :index, :destroy, :update ] do
    patch "mark_as_booked", to: "flight_bookings#mark_as_booked", as: :mark_as_booked
  end

  resources :users, only: [ :index ]
end

  # verb 'path', to: 'controller#action

app/models/trip.rb
class Trip < ApplicationRecord
  FLIGHT_CLASSES = ["Economy", "Premium Economy", "Business", "First Class"]
  
  # 1:N relationship:
  belongs_to :host, foreign_key: :user_id, class_name: "User"

  # N:N relationships:
  has_many :users_trips, dependent: :destroy
  has_many :users, through: :users_trips

  has_many :flight_bookings, dependent: :destroy

  has_many :invitations, dependent: :destroy

  # Cloudinary:
  has_one_attached :photo

  # Validation:
  validates :name, :city, :country, presence: true
  validates :name, uniqueness: true
  validates :start_date, :end_date, presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    if current_user.host
      @trips = current_user.owned_trips
    else
      @trips = current_user.trips
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @invitation = Invitation.new
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @host = current_user
    @trip.host = @host

    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :street, :zip, :city, :country, :start_date, :end_date, :airport_code, :max_price, :flight_class, :latest_arrival, :earliest_departure, :description, :photo)
  end
end

app/views/trips/edit.html.erb
<%= simple_form_for @trip do |f| %>

<div class="card p-5 col-12">
  <div class="card-body pt-10">
    <div class="row justify-content-center">
      <div class="col-6 pt-10">
        <h2 class="text-center mt-5 mb-5">Edit '<%= @trip.name.capitalize %>'</h2>
       
        <%= f.input :name, label: "Name" %>
        <%= f.input :street, label: "Street" %>
        <%= f.input :zip, label: "Zip code" %>
        <%= f.input :city, label: "City" %>
        <%= f.input :country, label: "Country", as: :string %>
        <%= f.input :start_date, label: "Start date", as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, label: "End date", as: :string, required: false, input_html: {class: "datepicker"} %>

      </div>
    </div>
  </div>
</div>

<div class="row_new justify-space-between">
  <div class="card col-6">
    <div class="card-body pt-12 d-flex">
      <div class="row col-12 justify-content-center">
        <div class="col-12 mt-4 mb-4">
          <%= f.input :description, as: :text, :input_html => {:rows => 10}%>
          <%= f.input :photo, as: :file, input_html: { class: 'd-none hidden', id: 'photo-input'}, label_html: { class: 'btn btn-primary'}, label: 'Upload new picture' %>
        </div>
      </div>
    </div>
  </div>
  <div class="card col-6">
    <div class="card-body pt-12 d-flex justify-content-center align-items-center preview-box">
      <div>
        <% if @trip.photo.attached? %>
          <%= cl_image_tag @trip.photo.key, class: "hidden", id: "photo-preview" %>
        <% else %>
          <%= cl_image_tag "https://res.cloudinary.com/hachiles/image/upload/w_300,h_300,c_scale/v1606993472/128729957_1019923191814990_8999176841093007894_n_axnirc.png", class: "hidden", id: "photo-preview" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  
<div class="card p-5 col-12">
  <div class="card-body pt-10">
    <div class="row justify-content-center">
      <div class="col-6 pt-10">
        <h2 class="text-center mt-5 mb-5">Edit restrictions</h2>
        <%= f.input :airport_code, label: "Airport (IATA code)" %>
        <%= f.input :max_price, label: "Max price (€)", as: :numeric %>
        <%= f.input :flight_class, label: "Travel class", collection: Trip::FLIGHT_CLASSES %>
        <div class="row">
          <div class="col-6">
            <%= f.input :latest_arrival, label: "Latest allowed event arrival", as: :string, required: false, input_html: {id: "latest_arrival"} %>
          </div>
          <div class="col-6">
            <%= f.input :earliest_departure, label: "Earliest allowed event departure", as: :string, required: false, input_html: {id: "earliest_departure"} %>
          </div>
        </div>
        <div class="row justify-content-center mt-4" >
          <%= f.submit class: "btn btn-primary" %>         
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/trips/index.html.erb
<% if current_user.host %>

  <div class="row">
    <div class="col">
      <div class="card mt-5">
        <div class="card-body">
          <div class="contact-list">
            <div class="contact-list-header">
              <h2 class="float-left">My trips</h2>
              <%= link_to "Create a trip", new_trip_path, class: "btn btn-primary float-right" %>
            </div>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Name</th>
                    <th scope="col">Dates</th>
                    <th scope="col">Location</th>
                    <th scope="col">Confirmed</th>
                    <th scope="col">Pending</th>
                  </tr>
                </thead>
                <tbody>
                  <% @trips.each do |trip| %>
                    <% pending = trip.invitations.where(status: "Pending") %>
                    <tr class='clickable-row' onclick="window.location='<%= trip_url(trip) %>';">
                      <th></th>
                      <td><%= trip.name.split.map(&:capitalize).join(' ') %></td>
                      <td><%= "#{trip.start_date.strftime("%d/%m/%Y")} - #{trip.end_date.strftime("%d/%m/%Y")}" %></td>
                      <td><%= trip.city.split.map(&:capitalize).join(' ') %>, <%= trip.country.upcase %></td>
                      <td><%= trip.users.length %></td>
                      <td><%= pending.length %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div> 
        </div>
      </div>
    </div>
  </div>

<% else %>

  <div class="row">
    <div class="col">
      <div class="card mt-5">
        <div class="card-body">
          <div class="contact-list">
            <div class="contact-list-header">
              <h2 class="float-left">My trips</h2>
            </div>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Name</th>
                    <th scope="col">Dates</th>
                    <th scope="col">Location</th>
                    <th scope="col">Flight booked?</th>
                  </tr>
                </thead>
                <tbody>
                  <% @trips.each do |trip| %>
                    <% pending = trip.invitations.where(status: "Pending") %>
                    <tr class='clickable-row' onclick="window.location='<%= trip_url(trip) %>';">
                      <th></th>
                      <td><%= trip.name.split.map(&:capitalize).join(' ') %></td>
                      <td><%= "#{trip.start_date.strftime("%d/%m/%Y")} - #{trip.end_date.strftime("%d/%m/%Y")}" %></td>
                      <td><%= trip.city.split.map(&:capitalize).join(' ') %>, <%= trip.country.upcase %></td>
                      <% if FlightBooking.where(trip_id: trip.id).where(user_id: current_user.id).exists? %>
                        <td><%= "Yes" %></td>
                      <% else %>
                        <td><%= "No" %></td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div> 
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/trips/new.html.erb
<%= simple_form_for @trip do |f| %>
<div class="card p-12">
  <div class="card-body pt-10">
    <div class="row justify-content-center">
      <div class="col-6 pt-10">
        <h2 class="text-center mt-5 mb-5">Create a trip</h2>
          <%= f.input :name, label: "Trip Name" %>
          <%= f.input :street, label: "Address" %>
          <div class="row">
            <div class="col-6">
              <%= f.input :zip, label: "Zip code" %>
            </div>
            <div class="col-6">
              <%= f.input :city, label: "City" %>
            </div>
          </div>
          <%= f.input :country, label: "Country", as: :string %>
          <div class="row">
            <div class="col-6 mb-5">
              <%= f.input :start_date, label: "Start date", as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>
            <div class="col-6 mb-5">
              <%= f.input :end_date, label: "End date", as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row_new justify-space-between">
    <div class="card col-6">
      <div class="card-body pt-12 d-flex">
        <div class="row col-12 justify-content-center">
          <div class="col-12 mt-4 mb-4">
            <%= f.input :description, as: :text, :input_html => {:rows => 10}%>
            <%= f.input :photo, as: :file, input_html: { class: 'd-none hidden', id: 'photo-input'}, label_html: { class: 'btn btn-primary'}, label: 'Upload picture' %>
          </div>
        </div>
      </div>
    </div>
    <div class="card col-6">
      <div class="card-body pt-12 d-flex justify-content-center align-items-center preview-box">
        <div>
          <!--<%= image_tag "", class: "hidden", id: "photo-preview" %>-->
          <%= cl_image_tag "https://res.cloudinary.com/hachiles/image/upload/w_300,h_300,c_scale/v1606993472/128729957_1019923191814990_8999176841093007894_n_axnirc.png", class: "hidden", id: "photo-preview" %>
        </div>
      </div>
    </div>
  </div>


  <div class="card p-10">
    <div class="card-body pt-10">
      <div class="row justify-content-center">
        <div class="col-6 pt-10">
          <h2 class="text-center mt-5 mb-5">Restrictions</h2>
          <%= f.input :airport_code, label: "Airport (IATA code)" %>
          <%= f.input :max_price, label: "Price ceilling (€)", as: :numeric %>
          <%= f.input :flight_class, label: "Travel class", collection: Trip::FLIGHT_CLASSES %>
          <div class="row">
            <div class="col-6">
              <%= f.input :latest_arrival, label: "Latest arrival", as: :string, required: false, input_html: {id: "latest_arrival"} %>
            </div>
            <div class="col-6">
                <%= f.input :earliest_departure, label: "Earliest departure", as: :string, required: false, input_html: {id: "earliest_departure"} %>
            </div>
          </div>
          <div class="row justify-content-center mt-4" >
            <%= f.submit class: "btn btn-primary mb-5" %>
          </div>      
      </div>
    </div>
  </div>`
</div>
<%end%>

app/views/trips/show.html.erb
<div class="row">
      <div class="col-lg-12">
        <div class="profile-cover">
          <% if @trip.photo.attached? %>
            <%= cl_image_tag @trip.photo.key %>
          <% else %>
            <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483935/profile-bg_zh4oi2.jpg">
          <% end %>
        </div>
        <div class="profile-header">
          <div class="profile-img">
            <% if @trip.host.photo.attached? %>
              <%= cl_image_tag @trip.host.photo.key %>
            <% else %>
              <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483934/avatar3_znnvez.png">
            <% end %>
          </div>
          <div class="profile-name">
            <h3><%= @trip.name.split.map(&:capitalize).join(' ') %></h3>
          </div>
          <div class="profile-header-menu">
            <ul class="list-unstyled">
              <% if current_user == @trip.host %>
                <li><%= link_to "Edit trip", edit_trip_path, class:"btn btn-outline-primary" %></li>
                <li><%= link_to "Delete trip", trip_path, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-primary" %></li>
              <% else %>
                <li><%= link_to "Search flights", trip_search_flights_path(@trip.id), class:"btn btn-outline-primary" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

<div class="trip-inside no-page-title contacts-app p-0">
  <div id="main-wrapper">
  </div> 
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Details</h5>
          <ul class="list-unstyled">
            <li class="mb-2"><!-- <strong>Address:</strong> --><i class="fas fa-map-marker-alt"></i> <%= @trip.street.split.map(&:capitalize).join(' ') %>,<br> <%= @trip.zip %> <%= @trip.city.capitalize %>,<br> <%= @trip.country.upcase %></li>
            <li><!-- <strong>Start:</strong> --><i class="far fa-calendar-alt"></i> <%= @trip.start_date.strftime("%b, %d %Y") %> - <%= @trip.end_date.strftime("%b, %d %Y") %></li>
            <!-- <li><strong>End:</strong> <%= @trip.end_date.strftime("%d/%m/%Y") %></li><br> -->
          </ul>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Restrictions</h5>
            <ul class="list-unstyled">
              <li class="mb-1"><strong>Arrival airport:</strong> <%= @trip.airport_code.nil? ? "N/A" : @trip.airport_code.upcase %></li>
              <li class="mb-1"><strong>Price ceilling:</strong> <%= @trip.max_price.nil? ? "N/A" : "#{@trip.max_price}€" %></li>
              <li class="mb-1"><strong>Travel class:</strong> <%= @trip.flight_class.nil? || @trip.flight_class == "" ? "N/A" : @trip.flight_class.capitalize %></li>
              <li class="mb-1"><strong>Latest arrival:</strong> <%= @trip.latest_arrival.nil? ? "N/A" : @trip.latest_arrival.strftime("%b, %d %Y - %H:%M") %></li>
              <li class="mb-1"><strong>Earliest departure:</strong> <%= @trip.earliest_departure.nil? ? "N/A" : @trip.earliest_departure.strftime("%b, %d %Y - %H:%M") %></li>
            </ul>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="post">
            <h5 class="card-title">Trip description</h5>
            <p><%= @trip.description %></p>
          </div>
        </div>
      </div>
      <% if current_user == @trip.host %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Send invitations</h5>
            <%= simple_form_for [@trip, @invitation] do |f| %>
              <%= f.input :email, label: "Email address" %>
              <%= f.submit "Invite", class:"btn btn-primary" %>
            <% end %> <br>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-3">
      <% if current_user != @trip.host %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Host contact Info</h5>
          <ul class="list-unstyled profile-about-list">
            <li><strong>Name:</strong> <%= @trip.host.first_name.capitalize %> <%= @trip.host.last_name.capitalize %></li>
            <li><strong>Email:</strong> <%= @trip.host.email %></li>
          </ul>
        </div>
      </div>
      <% end %>
      <% if @trip.users.count > 0 %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Participants</h5>
          <div class="story-list">
            <% @trip.users.each do |participant| %>
              <div class="story">
                <% if participant.photo.attached? %>
                  <%= cl_image_tag participant.photo.key %>
                <% else %>
                  <% random_index = rand(1..5) %>
                  <% case random_index %>
                  <% when 1 %>
                  <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483934/avatar3_znnvez.png" alt="">
                  <% when 2 %>
                  <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483934/avatar1_fujnmo.png" alt="">
                  <% when 3 %>
                  <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483934/avatar2_da1iqq.png" alt="">
                  <% when 4 %>
                  <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483935/avatar5_ikfpkw.png" alt="">
                  <% when 5 %>
                  <img src="https://res.cloudinary.com/hachiles/image/upload/v1606483935/avatar4_l74h38.png" alt="">
                  <% end %>
                <% end %>
                <div class="story-info">
                  <span class="story-author"><%= participant.first_name.capitalize %><br><%= participant.last_name.capitalize %></span>
                </div>
              </div>
            <% end %> 
          </div>
        </div>
      </div>
      <% end %>
      <% if current_user == @trip.host %>
      <% pending = @trip.invitations.where(status: "Pending") %>
        <% if pending.length > 0 %>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Pending invitations</h5>
              <div class="list-unstyled">
                <% @trip.invitations.each do |invitation| %>
                  <% if invitation.status == "Pending" %>
                    <div class="story">
                      <div class="story-info">
                        <%= invitation.email %><br><%= invitation.created_at.strftime("%b, %d %Y - %H:%M") %> (UTC)
                      </div><br>
                    </div>
                  <% end %>
                <% end %> 
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div><!-- Main Wrapper -->


<%# Old Code %>

<%
=begin %>
<% if current_user == @trip.host %>
  <div class="container mt-3 mb-3">
    <%= link_to "Edit trip", edit_trip_path, class:"btn btn-primary" %>
  </div>

  <div class="container mt-3 mb-3">
    <%= link_to "Delete trip", trip_path, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-primary" %>
  </div>
<% end %>

<div class="container mt-5">
  <h1><%= @trip.name.capitalize %></h1>
  <h3>Details:</h3>
  <ul>
    <li>Address: <%= @trip.street.capitalize %>, <%= @trip.zip %> <%= @trip.city.capitalize %>, <%= @trip.country.upcase %></li>
    <li>Start: <%= @trip.start_date %></li>
    <li>End: <%= @trip.end_date %></li>
  </ul>
  <h3>Restrictions:</h3>
  <ul>
    <li>Arrival airport: <%= @trip.airport_code.nil? ? "N/A" : @trip.airport_code.upcase %></li>
    <li>Price ceilling: <%= @trip.max_price.nil? ? "N/A" : @trip.max_price %>€</li>
    <li>Travel class: <%= @trip.flight_class.nil? ? "N/A" : @trip.flight_class.capitalize %></li>
    <li>Latest arrival: <%= @trip.latest_arrival.nil? ? "N/A" : @trip.latest_arrival %></li>
    <li>Earliest departure: <%= @trip.earliest_departure.nil? ? "N/A" : @trip.earliest_departure %></li>
  </ul>
  <% if @trip.users.count > 0 %>
  <h3>Participants:</h3>
  <ul>
    <% @trip.users.each do |participant| %>
      <li><%= participant.first_name.capitalize %> <%= participant.last_name.capitalize %></li>
    <% end %>
  </ul>
  <% end %>
  <% if current_user == @trip.host %>
    <% if @trip.invitations.length > 0 %>
      <h3>Pending invitations:</h3>
      <ul>
        <% @trip.invitations.each do |invitation| %>
          <% if invitation.status == "Pending" %>
            <li><%= invitation.email %><br>Creation: <%= invitation.created_at %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  <% end %>

  <% if current_user == @trip.host %>
    <h3>Create invitations:</h3>
    <%= simple_form_for [@trip, @invitation] do |f| %>
      <%= f.input :email, label: "Email address" %>
      <%= f.submit "Invite!", class:"btn btn-primary" %>
    <% end %> <br>
  <% end %>

  <%= link_to "Back to My trips", trips_path, class:"btn btn-primary" %>
</div>
<%
=end %>