config/routes.rb
Rails.application.routes.draw do
  post 'search_flights', to: 'flight_bookings#find_location'
  delete 'search_flights', to: 'flight_bookings#destroy_flight_selection'
  
  devise_for :users
  root to: 'pages#home'

  resources :trips do
    resources :invitations, only: [ :new, :create ]
    resources :flight_bookings, only: [ :new, :create ]
    get 'search_flights', to: 'flight_bookings#flight_search'
  end
  
  resources :invitations, only: [ :index, :show, :update ]

  resources :flight_bookings, only: [ :index, :destroy, :update ] do
    patch "mark_as_booked", to: "flight_bookings#mark_as_booked", as: :mark_as_booked
  end

  resources :users, only: [ :index ]
end

  # verb 'path', to: 'controller#action

app/models/flight_booking.rb
class FlightBooking < ApplicationRecord

  # 1:N relationships:
  belongs_to :user
  belongs_to :trip
end

app/controllers/flight_bookings_controller.rb
# require 'json'
# require 'open-uri'
class FlightBookingsController < ApplicationController

  def index
    if current_user.host
      host_trips = current_user.owned_trips
      trips_unsorted = []
      host_trips.each do |host_trip|
        if FlightBooking.where(trip_id: host_trip.id).length > 0
          trips_unsorted << host_trip
        end
      end
      @trips = trips_unsorted.sort_by(&:created_at).reverse
    else
      flight_bookings_unsorted = FlightBooking.where(user_id: current_user.id)
      @flight_bookings = flight_bookings_unsorted.sort_by(&:created_at).reverse
    end
  end

  def mark_as_booked
    @flight_booking = FlightBooking.find(params[:flight_booking_id])
    @flight_booking.update(booked: true)
    redirect_to flight_bookings_path
  end

  def flight_search
    @flight_booking = FlightBooking.new
    @trip = Trip.find(params[:trip_id])
  end

  def new
    @flight_booking = FlightBooking.new
    @trip = Trip.find(params[:trip_id])

  end

  def create
    @trip = Trip.find(params[:trip_id])
    flight_hash = params[:flight_booking]
    flight_hash = JSON.parse(flight_hash)

    save_flight_selection(flight_hash["outbound"])
    save_flight_selection(flight_hash["inbound"])
  end

  def save_flight_selection(strong_params)
    @flight_booking = FlightBooking.new(strong_params)
    @flight_booking.user = current_user
    @flight_booking.trip = @trip
    @flight_booking.flight_class = assign_class(@flight_booking.flight_class)
    # @flight_booking.airline = assign_airline_name(@flight_booking.airline)
    if @flight_booking.save
      puts "Flight Saved!"
    else
      puts "Not saved!"
    end

  end

  def destroy_flight_selection
    p params
    p params[:booking_link]
    @flights = FlightBooking.all
    @flights = @flights.select { |flight| flight[:booking_link] == params[:booking_link] }
    @flights.each { |flight| flight.destroy }
  end

  def destroy
    @flight_booking = FlightBooking.find[:id]
    @flight_booking.destroy
  end


  def assign_class(class_code)

    case class_code
    when "M"
      "Economy"
    when "W"
      "Premium Economy"
    when "C"
      "Business"
    when "F"
      "First"
    else
      "No class assigned"
    end
  end

  # def assign_airline_name(airline_iata)
  #   url = "https://api.skypicker.com/carriers"
  #   url_content = open(url).read
  #   carriers = JSON.parse(url_content)

  #   airline_info = carriers.find { |carrier| carrier["id"] == airline_iata }
  #   airline_info["name"]
  # end

  # def destroy_flight_booking_selection
  #    @flight_booking = FlightBooking.find[:booking_link]
  #     @flight_booking.destroy
  # end

private

  # def flight_params_outbound
  #   # params.require(:flight_booking).permit(:departure_airport_code, :arrival_airport_code, :airline, :flight_number, :price, :flight_class, :booking_link, :departure_date_local, :arrival_date_local, :departure_date_utc, :arrival_date_utc, :booked)
  #   json_params = ActionController::Parameters.new(JSON.parse(params[:flight_booking]))
  #   json_params.require(:flight_booking).permit(outbound:[:departure_airport_code, :arrival_airport_code, :airline, :flight_number, :price, :flight_class, :booking_link, :departure_date_local, :arrival_date_local, :departure_date_utc, :arrival_date_utc, :booked])
  # end

  # def flight_params_inbound
  #   # params.require(:flight_booking).permit(:departure_airport_code, :arrival_airport_code, :airline, :flight_number, :price, :flight_class, :booking_link, :departure_date_local, :arrival_date_local, :departure_date_utc, :arrival_date_utc, :booked)
  #   json_params = ActionController::Parameters.new(JSON.parse(params[:flight_booking]))
  #   json_params.require(:flight_booking).permit(inbound:[:departure_airport_code, :arrival_airport_code, :airline, :flight_number, :price, :flight_class, :booking_link, :departure_date_local, :arrival_date_local, :departure_date_utc, :arrival_date_utc, :booked])
  # end

end

app/views/flight_bookings/flight_search.html.erb
<%# DO NOT REMOVE -  hidden div to get trip id %>
<div id="trip" data-id="<%= params[:trip_id] %>"></div>
<%# ---------------------------------------------- %>
<!--traveler restriction card-->
<div class="container mt-5 mb-5 rounded restrictions-card shadow">
  <h1 class="pb-4 mb-4">Booking Restrictions for '<%=@trip.name %>'</h1>
  <div class="d-flex justify-content-between booking-restrictions">
    <div>
      <div class="">
        <i class="far fa-calendar-alt text-primary"></i>
        Start date
      </div>
      <p class="font-weight-bold text-center"><%= @trip.start_date.strftime("%b, %d %Y") %></p>
    </div>
    <div>
      <div class="">
        <i class="far fa-calendar-alt text-primary"></i>
        End date
      </div>
      <p class="font-weight-bold text-center"><%= @trip.end_date.strftime("%b, %d %Y") %></p>
    </div>
    <div>
      <div class="">
        <i class="fas fa-plane text-primary"></i>
        Arrival airport
      </div>
      <p class="font-weight-bold"><%= @trip.airport_code.nil? ? "N/A" : @trip.airport_code.upcase %></p>
    </div>
    <div>
      <div class="">
        <i class="fas fa-money-bill text-primary"></i>
        Price ceiling
      </div>
      <p class="font-weight-bold"><%= @trip.max_price.nil? ? "N/A" : "#{@trip.max_price}€" %></p>
    </div>
    <div>
      <div class="align-items-center passenger">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="purple" xmlns="http://www.w3.org/2000/svg">
          <path d="M3.59 2.80133C2.81 2.1615 2.81 1.11971 3.59 0.479877C4.37 -0.159959 5.64 -0.159959 6.42 0.479877C7.2 1.11971 7.2 2.1615 6.42 2.80133C5.63 3.44937 4.37 3.44937 3.59 2.80133ZM2 11.4883V4.10561H0V11.4883C0 13.7524 2.24 15.5898 5 15.5898H11V13.9492H5C3.34 13.9492 2 12.85 2 11.4883ZM16 14.827L10.93 10.668H7.5V7.64932C8.9 8.59267 11.1 9.42117 13 9.42117V7.64932C11.34 7.66573 9.39 6.93566 8.33 5.9759L6.93 4.70444C6.74 4.53217 6.5 4.39272 6.24 4.29428C5.95 4.17944 5.62 4.10561 5.28 4.10561H5.25C4.01 4.10561 3 4.93412 3 5.9513V10.668C3 12.0297 4.34 13.1289 6 13.1289H11.07L14.57 16L16 14.827Z" fill="#8605b4"/>
        </svg>
        Travel class
      </div>
      <p class="font-weight-bold"><%= @trip.flight_class.nil? || @trip.flight_class == "" ? "N/A" : @trip.flight_class.capitalize %></p>
    </div>
    <div>
      <div class="">
        <i class="fas fa-clock text-primary"></i>
        Latest arrival
      </div>
      <p class="font-weight-bold"><%= @trip.latest_arrival.nil? ? "N/A" : @trip.latest_arrival.strftime("%d/%m/%Y") %></p>
    </div>
    <div>
      <div class="">
        <i class="fas fa-clock text-primary"></i>
        Earliest departure
      </div>
      <p class="font-weight-bold"><%= @trip.earliest_departure.nil? ? "N/A" : @trip.earliest_departure.strftime("%d/%m/%Y") %></p>
    </div>
  </div>
</div>

<!--js flight searchbox-->
<div class="container mt-5 mb-5 rounded flight-searchbox shadow">
  <div class="row mb-3 ml-1">
    <h1 class="text-light mt-3">Flight Search</h1>
  </div>
  <form>
    <div class="row">
      <select class="col-2 mt-2 mb-3 ml-4 mdb-select md-form travel-class-dropdown" id="fare-class">
        <option value="M">Economy</option>
        <option value="W">Premium Economy</option>
        <option value="C">Business</option>
        <option value="F">First</option>
      </select>

      <%# <select class="col-2 mdb-select md-form"id="route">
        <option value="round">Round trip</option>
        <option value="oneway">One way</option>
      </select> %>
    </div>

    <div class="form-row">
      <div class="col ml-2 mb-5">
        <input type="text" class="form-control" placeholder="BER" id="obDepartureAp">
        <%# <input type="text" class="form-control" placeholder="BER" id="autocomplete"> %>
        <div class="autofill-airport pl-3" id="departure-airports"></div>
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="FRA" id="obArrivalAp">
        <div class="autofill-airport pl-3" id="arrival-airports"></div>
      </div>
      <div class="col">
        <input type="text" class="form-control datepicker lighter" placeholder="Departure Date" id="ob_date">
      </div>
      <div class="col">
        <input type="text" class="form-control datepicker lighter" placeholder="Return Date" id="ib_date">
      </div>

      <div class="col mt-2 ml-2 align-self-start mt-n1">
        <button type="button" class="btn-lg w-100 flight-search-button shadow" id="search">Search</button>

      </div>
    </div>

  </div>
  </form>

<%# Spinner %>
  <div class="d-flex justify-content-center">
    <div id="loading-spinner" class="spinner-border text-secondary mt-20" style="width: 10rem; height: 10rem; display: none; margin: 150px" role="status" >
      <span class="sr-only">Loading...</span>
    </div>
  </div>

  <!--js flight list & confirm button-->
  <div class="container" id="flight-list"></div>
  <%# This button has styled display none becasue of js purposes %>
  <div class="row justify-content-center">
    <button class="btn btn-primary btn-lg rounded-pill w-50 pt-2 mt-5 mb-5" id="select-flights" data-toggle="modal" data-target="#flightConfirm" style="display: none;">Confirm Selection</button>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="flightConfirm" tabindex="-1" role="dialog" aria-labelledby="flightConfirmLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body mt-3">
        <h4><strong>YOUR FLIGHT SELECTION HAS BEEN SAVED!</strong></h3>
         <br>
        <h4>Please click continue to view your flights or cancel to go back and make a new seclection.</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= link_to "Continue", flight_bookings_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/flight_bookings/index.html.erb
<!-- This is the view -->
<!-- Host page -->
<% if current_user.host %>

  <div class="row">
    <div class="col">
      <div class="card mt-5">
        <div class="card-body">
          <div class="contact-list">
            <div class="contact-list-header">
              <h2 class="float-left mb-5">My flights <small>(All local times)</small></h2>
            </div>
            <% @trips.each do |trip| %>
              <div class="table-responsive">
              <h4><%= trip.name.split.map(&:capitalize).join(' ') %></h4>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col"></th>
                      <th scope="col">Passenger</th>
                      <th scope="col">Route</th>
                      <th scope="col">Departure</th>
                      <th scope="col">Arrival</th>
                      <th scope="col">FL#</th>
                      <th scope="col">Price</th>
                      <th scope="col">Book</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% trip.flight_bookings.each do |flight| %>
                      <tr>
                        <th></th>
                        <td><%= flight.user.first_name %><br><%= flight.user.last_name %></td>
                        <td><%= flight.departure_airport_code %><br><%= flight.arrival_airport_code %></td>
                        <td><%= flight.departure_date_local.strftime("%d/%m/%Y") %><br><%= flight.departure_date_local.strftime("%H:%M") %></td>
                        <td><%= flight.arrival_date_local.strftime("%d/%m/%Y") %><br><%= flight.arrival_date_local.strftime("%H:%M") %></td>
                        <td><%= flight.flight_number %><br><%= flight.airline %></td>
                        <td><%= flight.price %>€</td>
                        <td><%= link_to "Kiwi.com", flight.booking_link %></td>
                        <% if flight.booked %>
                          <td>Booked</td>
                        <% else %>
                          <td><%= link_to "Mark as booked", flight_booking_mark_as_booked_path(flight), method: :patch, class: "btn btn-primary", data: { confirm: "Mark this flight as booked?" } %></td>
                        <% end %>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            <% end %>
          </div> 
        </div>
      </div>
    </div>
  </div>

<% else %>

  <div class="row">
    <div class="col">
      <div class="card mt-5">
        <div class="card-body">
          <div class="contact-list">
            <div class="contact-list-header">
              <h2 class="float-left mb-5">My flights <small>(All local times)</small></h2>
            </div>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col"></th>
                      <th scope="col">Trip</th>
                      <th scope="col">Route</th>
                      <th scope="col">Departure</th>
                      <th scope="col">Arrival</th>
                      <th scope="col">FL#</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @flight_bookings.each do |flight| %>
                      <tr>
                        <th></th>
                        <td><%= flight.trip.name.split.map(&:capitalize).join(' ') %></td>
                        <td><%= flight.departure_airport_code %><br><%= flight.arrival_airport_code %></td>
                        <td><%= flight.departure_date_local.strftime("%d/%m/%Y") %><br><%= flight.departure_date_local.strftime("%H:%M") %></td>
                        <td><%= flight.arrival_date_local.strftime("%d/%m/%Y") %><br><%= flight.arrival_date_local.strftime("%H:%M") %></td>
                        <td><%= flight.flight_number %><br><%= flight.airline %></td>
                        <% if flight.booked %>
                          <td>Booked</td>
                        <% else %>
                          <td>Pending</td>
                        <% end %>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
          </div> 
        </div>
      </div>
    </div>
  </div>

<% end %>