config/routes.rb
Rails.application.routes.draw do
  post 'search_flights', to: 'flight_bookings#find_location'
  delete 'search_flights', to: 'flight_bookings#destroy_flight_selection'
  
  devise_for :users
  root to: 'pages#home'

  resources :trips do
    resources :invitations, only: [ :new, :create ]
    resources :flight_bookings, only: [ :new, :create ]
    get 'search_flights', to: 'flight_bookings#flight_search'
  end
  
  resources :invitations, only: [ :index, :show, :update ]

  resources :flight_bookings, only: [ :index, :destroy, :update ] do
    patch "mark_as_booked", to: "flight_bookings#mark_as_booked", as: :mark_as_booked
  end

  resources :users, only: [ :index ]
end

  # verb 'path', to: 'controller#action

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%
=begin %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1>flyinvite</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li>
          <p class="greeting">Hi <%= current_user.first_name.capitalize %></p>
        </li>

        <% if current_user.host %>
          <li class="nav-item active circle_green">
            <%= link_to new_trip_path do %>
              <%= image_tag "Vectorplane.png", class: "plane" %>
            <%end%>
          </li>
        <% end %>

        <li class="nav-item dropdown">
          <%= image_tag "profile.png", class: "avatar dropdown-toggle profile-icon", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% unless current_user.host %>
              <%= link_to "Invitations", invitations_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "My Trips", trips_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%
=end %>

<div class="page-sidebar">
  <div class="profile-menu">
    <%= link_to root_path do %>
       <%= image_tag "flyinvitelogo.png", :size => "40x40", class: "text-left"%> 
    <%end%>    
  </div>
  <div class="page-sidebar-inner">
    <div class="page-sidebar-menu">
      <% if user_signed_in? %>
        <ul>
          <li class="button-list">
            <%= link_to root_path, class: "pb-1" do %>
              <i class="fas fa-home fa-2x"></i>
              <p><small>Home</small></p>
            <%end%>  
          </li>
          <li class="button-list">
            <%= link_to trips_path, class: "pb-1" do %>
              <i class="fas fa-suitcase fa-2x"></i>
              <p><small>My Trips</small></p>
            <%end%>  
          </li>
          <li>
            <%= link_to flight_bookings_path, class: "pb-1" do %>
              <i class="fas fa-plane fa-2x"></i>
              <p><small>My Flights</small></p>
            <%end%>   
          </li>
          <% if current_user.host %>
            <li>
              <%= link_to new_trip_path, class: "pb-1" do %>
                <i class="fas fa-plus fa-2x"></i>
                <p><small>New Trip</small></p>
              <%end%>   
            </li>
             <li>
              <%= link_to users_path, class: "pb-1" do %>
                <i class="fas fa-user-friends fa-2x"></i>
                <p><small>Travellers</small></p>
              <%end%>   
            </li>
          <%end%>
            <% unless current_user.host %>
            <li>
              <%= link_to invitations_path, class: "pb-1" do %>
                <i class="fas fa-ticket-alt fa-2x"></i> 
                <p><small>Invites</small></p>  
              <%end%>   
            </li>
            <%end%>
          </ul>
        <%end%>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="settings-menu-btn">
        <a href="javascript:void(0)" id="toggle-fullscreen"><i class="fas fa-expand fa-lg"></i></a>
        <%= button_to destroy_user_session_path, method: "delete", class: "btn btn-outline-light log-out fa-lg" do %>
          <i class="fas fa-sign-out-alt"></i>
        <%end%>
      </div>
    <%end%>
</div><!-- /Page Sidebar -->







               